### ISSUE TITLE
Model loading error when conducting PPO experiment

### ISSUE THREAD

**Issue by neilwen987** [tlc4418/llm_optimization#17]
Hi, thanks for your work and code. I met model loading error when loading _reward-model-human_ to evaluate answers.
My questions are as follow:

1. How could I get the weights of _alpaca_farm_models/reward-model-human_ properly?
    I download the pretrained weights on website https://huggingface.co/tatsu-lab/alpaca-farm-reward-model-human-wdiff as mentioned in https://github.com/tatsu-lab/alpaca_farm. Is this a right move?  After doing so, I met the problem below with the following config in _config_rl.yaml_:

```
pythia_rlhf_individual:
  output_dir: runs/ppo_individual
  datasets:
    - alpaca_farm

  **gold_config:**
    model_name: tatsu-lab/alpaca-farm-reward-model-human-wdiff
    **is_alpacafarm_rm: False**
    batch_size: 32

  rank_config:
    is_reward_model: true
    model_names: 
      - models/rm-pythia-44m_seed1
    cache_dir: .cache
    pooling: last
    residual_dropout: 0.01
    use_flash_attention: false
    dtype: bf16
    batch_size: 128

  sft_config:
    is_reward_model: false
    model_name: tlc4418/pythia_1.4b_sft_policy
    pretrained_path : models/hf_pythia_1.4b_sft
    cache_dir: .cache
    quantization: false
    seq2seqmodel: false
    freeze_layer:
    num_layers_unfrozen: 2
    residual_dropout: 0.2
    use_flash_attention: false
    dtype: bf16
    batch_size: 32
```

<img width="1059" alt="image" src="https://github.com/user-attachments/assets/4b61f9ad-12db-4599-9650-47888f11db12">

2. I noticed that the  **is_alpacafarm_rm** is set to _False_ as default. Is this correct? Because after reading information on https://github.com/tatsu-lab/alpaca_farm, it seems that the golden reward used in PPO experiment is **alpacafarm_rm**?
